### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [dankincaid73/The-Scoop#8]
Grade: Exceeds Expectations

Awesome job on this project! You've implemented all of the routes with great skill and your code is well-formatted and commented. You did a great job of integrating your code into the codebase you were given, which is important and can be challenging if your formatting conventions don't line up. But you've done it well! 

I would only warn you that while commenting is super valuable and you should continue to do so, there is such a thing as over-commenting. Sometimes, you'd leave comments saying very straightforward note like 'Increment next comment id,' which was quite obvious to anyone reading your code. In-function comments are supposed to clarify potentially ambiguous or complicated lines and are not always necessary if the line is doing something basic or easy to understand. Just think about whether a reader would need clarity on a given operation or line before automatically writing something. This will also save you time and make it less tedious for you! Again, fantastic job here and congratulations!

**Comment by dankincaid73** [comment]
Thank you very much!!
I totally get and agree with you on the comments.  I just have had some CEO's that wanted to review code. :0 So I got in the habit of writing comments for programmers as well as non programmers.  I'll cut them down to the important things.
Thanks again!
